apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app
          image: todo-app:latest
          envFrom:
            - configMapRef:
                name: todo-app-config
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/files